spring:
  profiles:
    active: dev


---
# 8004端口配置，就餐服务
server:
  port: 8004
#spring的配置
spring:
  profiles: dev
  application:
    name: smartmem-dining-service-povider-8004
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.109:5432/dining_service
    username: postgres
    password: postgres

# mybatis-plus配置
mybatis-plus:
  configuration:
    # 配置下划线转换为驼峰命名法
    map-underscore-to-camel-case: true
    # 日志打印查询sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 将数据库中为null的字段也取出
    call-setters-on-nulls: true

  mapper-locations: classpath*:mapper/*/*Mapper.xml
  type-aliases-package: com.cisdi.smartmem.pojo


# Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: smartmem-dining-service-povider-8004


# hystrix配置
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true #是否开启超时(默认开启)
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #超时时间(默认1000毫秒)